name: bot_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - sqlite
  - requests
  - python-dotenv
  - langchain
  - langchain-openai
  - pydantic
  - python-dateutil
  - jsonschema
  - openai
  - fastapi
  - unicorn

  # Optional packages for extended timezone and datetime support
  - tzdata
  - pytz

  # Testing dependencies
  - pytest
  - pytest-asyncio
  - pytest-mock
  - pytest-cov
  - coverage
  
  # PIP dependencies
  - pip:
      - aiogram
      - openai  # For OpenAI API access
      - typing-extensions  # Compatibility for typing in different Python versions
      - aioresponses  # For mocking HTTP requests in async tests
      - factory-boy  # For test data generation
      - dependency-injector  # Professional DI framework
      - google-api-python-client==2.88.0  # Google Calendar API
      - google-auth-httplib2==0.1.0  # Google Auth HTTP library
      - google-auth-oauthlib==1.0.0  # Google OAuth library
