version: '3.8'

services:
  bot-test:
    build:
      context: ../
      dockerfile: infra/Dockerfile
    environment:
      # Test environment variables
      - TELEGRAM_BOT_TOKEN=test_token_not_used
      - OPENAI_API_KEY=test_key_not_used
      - PYTHONPATH=/app
    volumes:
      # Mount source code for development
      - ../:/app
      # Mount test results output
      - ./test-results:/app/test-results
    working_dir: /app
    command: >
      bash -c "
        echo 'Installing test dependencies...' &&
        mamba install -y pytest pytest-asyncio pytest-mock pytest-cov coverage -c conda-forge &&
        pip install aioresponses factory-boy &&
        echo 'Running tests...' &&
        python -m pytest tests/ -v --cov=services --cov=platforms --cov=database --cov=models --cov=core --cov-report=term-missing --cov-report=html:/app/test-results/htmlcov --cov-report=xml:/app/test-results/coverage.xml --junit-xml=/app/test-results/junit.xml
      "
    networks:
      - test-network

networks:
  test-network:
    driver: bridge