"""Reusable AI workflow engine package."""

# F1.1 (lazy public surface): exports resolve on first attribute access (PEP 562), so a
# trivial consumer pays only for the facilities it touches — no second execution path,
# no lite package; every name below still resolves exactly as before.

from importlib import import_module
from typing import Any

__version__ = "0.8.1"

_EXPORTS: dict[str, tuple[str, str]] = {
    "AgentCapability": ("ai_workflow_engine.engine", "AgentCapability"),
    "AgentEpisodePlanner": ("ai_workflow_engine.engine", "AgentEpisodePlanner"),
    "AgentMemory": ("ai_workflow_engine.memory", "AgentMemory"),
    "AgentMemoryRenderContext": ("ai_workflow_engine.memory", "AgentMemoryRenderContext"),
    "AgentRunRequest": ("ai_workflow_engine.models", "AgentRunRequest"),
    "AgentRunResult": ("ai_workflow_engine.models", "AgentRunResult"),
    "AgentStepDecision": ("ai_workflow_engine.models", "AgentStepDecision"),
    "AgentToolCall": ("ai_workflow_engine.models", "AgentToolCall"),
    "AgentToolStep": ("ai_workflow_engine.models", "AgentToolStep"),
    "AsyncQueueDetailSink": ("ai_workflow_engine.engine", "AsyncQueueDetailSink"),
    "AsyncQueueTraceSink": ("ai_workflow_engine.engine", "AsyncQueueTraceSink"),
    "AsyncQueueUsageSink": ("ai_workflow_engine.usage", "AsyncQueueUsageSink"),
    "BranchDecision": ("ai_workflow_engine.workflow", "BranchDecision"),
    "BranchFlowNode": ("ai_workflow_engine.flow_authoring", "BranchFlowNode"),
    "CallbackTraceSink": ("ai_workflow_engine.engine", "CallbackTraceSink"),
    "CapabilityBindingError": ("ai_workflow_engine.executor", "CapabilityBindingError"),
    "CapabilityCall": ("ai_workflow_engine.engine", "CapabilityCall"),
    "CapabilityContext": ("ai_workflow_engine.models", "CapabilityContext"),
    "CapabilityRegistry": ("ai_workflow_engine.engine", "CapabilityRegistry"),
    "CapabilityResult": ("ai_workflow_engine.models", "CapabilityResult"),
    "CapabilityRuntime": ("ai_workflow_engine.engine", "CapabilityRuntime"),
    "CapabilitySpec": ("ai_workflow_engine.models", "CapabilitySpec"),
    "ChatMessage": ("ai_workflow_engine.llm_protocol", "ChatMessage"),
    "CheckpointStore": ("ai_workflow_engine.engine", "CheckpointStore"),
    "ClarificationOption": ("ai_workflow_engine.models", "ClarificationOption"),
    "CompactingMemory": ("ai_workflow_engine.memory", "CompactingMemory"),
    "DEFAULT_FLOW_AUTHOR_PROMPT": ("ai_workflow_engine.flow_authoring", "DEFAULT_FLOW_AUTHOR_PROMPT"),
    "DetailSink": ("ai_workflow_engine.engine", "DetailSink"),
    "END": ("ai_workflow_engine.workflow", "END"),
    "EvaluateFlowNode": ("ai_workflow_engine.flow_authoring", "EvaluateFlowNode"),
    "EvaluationController": ("ai_workflow_engine.engine", "EvaluationController"),
    "EvaluationPlanner": ("ai_workflow_engine.engine", "EvaluationPlanner"),
    "EvidenceRef": ("ai_workflow_engine.models", "EvidenceRef"),
    "ExternalAdapterCapability": ("ai_workflow_engine.engine", "ExternalAdapterCapability"),
    "ExternalProcessCapability": ("ai_workflow_engine.engine", "ExternalProcessCapability"),
    "ExternalProcessRequest": ("ai_workflow_engine.engine", "ExternalProcessRequest"),
    "ExternalWriteRequest": ("ai_workflow_engine.models", "ExternalWriteRequest"),
    "ExternalWriteResult": ("ai_workflow_engine.models", "ExternalWriteResult"),
    "Fallback": ("ai_workflow_engine.workflow", "Fallback"),
    "FanoutFlowNode": ("ai_workflow_engine.flow_authoring", "FanoutFlowNode"),
    "FlowArtifact": ("ai_workflow_engine.flow_authoring", "FlowArtifact"),
    "FlowAuthorRequest": ("ai_workflow_engine.flow_authoring", "FlowAuthorRequest"),
    "FlowNode": ("ai_workflow_engine.flow_authoring", "FlowNode"),
    "FlowNodeSpec": ("ai_workflow_engine.flow_authoring", "FlowNodeSpec"),
    "FullReplayMemory": ("ai_workflow_engine.memory", "FullReplayMemory"),
    "HumanClarificationCapability": ("ai_workflow_engine.engine", "HumanClarificationCapability"),
    "HumanClarificationChannel": ("ai_workflow_engine.engine", "HumanClarificationChannel"),
    "HumanClarificationRequest": ("ai_workflow_engine.models", "HumanClarificationRequest"),
    "HumanClarificationResponse": ("ai_workflow_engine.models", "HumanClarificationResponse"),
    "ImageEvictingMemory": ("ai_workflow_engine.memory", "ImageEvictingMemory"),
    "ImageInput": ("ai_workflow_engine.vision", "ImageInput"),
    "InMemoryCheckpointStore": ("ai_workflow_engine.engine", "InMemoryCheckpointStore"),
    "InMemoryDetailSink": ("ai_workflow_engine.engine", "InMemoryDetailSink"),
    "InMemoryExternalWriteSink": ("ai_workflow_engine.engine", "InMemoryExternalWriteSink"),
    "InMemoryHumanClarificationChannel": ("ai_workflow_engine.engine", "InMemoryHumanClarificationChannel"),
    "InMemoryMemoryStore": ("ai_workflow_engine.memory", "InMemoryMemoryStore"),
    "InMemoryTraceSink": ("ai_workflow_engine.engine", "InMemoryTraceSink"),
    "InMemoryUsageSink": ("ai_workflow_engine.usage", "InMemoryUsageSink"),
    "JsonlCheckpointStore": ("ai_workflow_engine.engine", "JsonlCheckpointStore"),
    "JsonlDetailSink": ("ai_workflow_engine.engine", "JsonlDetailSink"),
    "JsonlExternalWriteSink": ("ai_workflow_engine.engine", "JsonlExternalWriteSink"),
    "JsonlTraceSink": ("ai_workflow_engine.engine", "JsonlTraceSink"),
    "JsonlUsageSink": ("ai_workflow_engine.usage", "JsonlUsageSink"),
    "LLMAgentPlanner": ("ai_workflow_engine.engine", "LLMAgentPlanner"),
    "LLMCallable": ("ai_workflow_engine.llm_protocol", "LLMCallable"),
    "LLMRequest": ("ai_workflow_engine.llm_protocol", "LLMRequest"),
    "LLMResponse": ("ai_workflow_engine.llm_protocol", "LLMResponse"),
    "MachineSnapshot": ("ai_workflow_engine.snapshot", "MachineSnapshot"),
    "MemoryNamespace": ("ai_workflow_engine.memory", "MemoryNamespace"),
    "MemoryRecord": ("ai_workflow_engine.memory", "MemoryRecord"),
    "MemoryStore": ("ai_workflow_engine.memory", "MemoryStore"),
    "ModelProfile": ("ai_workflow_engine.models", "ModelProfile"),
    "NodeExecutionServices": ("ai_workflow_engine.node_services", "NodeExecutionServices"),
    "NodeExecutionState": ("ai_workflow_engine.executor", "NodeExecutionState"),
    "NodeResult": ("ai_workflow_engine.executor", "NodeResult"),
    "NodeSchedulingServices": ("ai_workflow_engine.node_services", "NodeSchedulingServices"),
    "ObservationConfig": ("ai_workflow_engine.config_loader", "ObservationConfig"),
    "ObservationDetail": ("ai_workflow_engine.models", "ObservationDetail"),
    "ObservationRunBundle": ("ai_workflow_engine.observation_bundle", "ObservationRunBundle"),
    "ObservationSequence": ("ai_workflow_engine.observation_bundle", "ObservationSequence"),
    "PlanArtifact": ("ai_workflow_engine.planning", "PlanArtifact"),
    "PlanTask": ("ai_workflow_engine.planning", "PlanTask"),
    "PromptCapturingLLMClient": ("ai_workflow_engine.prompt_capture", "PromptCapturingLLMClient"),
    "PromptRef": ("ai_workflow_engine.prompt_rendering", "PromptRef"),
    "PromptRenderError": ("ai_workflow_engine.prompt_rendering", "PromptRenderError"),
    "PromptRenderResult": ("ai_workflow_engine.prompt_rendering", "PromptRenderResult"),
    "PromptRenderService": ("ai_workflow_engine.prompt_rendering", "PromptRenderService"),
    "PromptRenderer": ("ai_workflow_engine.prompt_rendering", "PromptRenderer"),
    "PromptTemplateLoader": ("ai_workflow_engine.prompt_loader", "PromptTemplateLoader"),
    "Replan": ("ai_workflow_engine.workflow", "Replan"),
    "ReplayPlanner": ("ai_workflow_engine.engine", "ReplayPlanner"),
    "Retrace": ("ai_workflow_engine.workflow", "Retrace"),
    "Retry": ("ai_workflow_engine.workflow", "Retry"),
    "RuntimePlan": ("ai_workflow_engine.models", "RuntimePlan"),
    "RuntimePlanCompiler": ("ai_workflow_engine.engine", "RuntimePlanCompiler"),
    "SchedulingDecision": ("ai_workflow_engine.engine", "SchedulingDecision"),
    "SequencedDetailSink": ("ai_workflow_engine.observation_bundle", "SequencedDetailSink"),
    "SequencedTraceSink": ("ai_workflow_engine.observation_bundle", "SequencedTraceSink"),
    "SequencedUsageSink": ("ai_workflow_engine.observation_bundle", "SequencedUsageSink"),
    "SessionState": ("ai_workflow_engine.models", "SessionState"),
    "StepFlowNode": ("ai_workflow_engine.flow_authoring", "StepFlowNode"),
    "StructuredLLMNode": ("ai_workflow_engine.engine", "StructuredLLMNode"),
    "StructuredOutputError": ("ai_workflow_engine.engine", "StructuredOutputError"),
    "StructuredStateMemory": ("ai_workflow_engine.memory", "StructuredStateMemory"),
    "StructuredVisionLLMNode": ("ai_workflow_engine.vision", "StructuredVisionLLMNode"),
    "SubworkflowRef": ("ai_workflow_engine.workflow", "SubworkflowRef"),
    "TeeDetailSink": ("ai_workflow_engine.engine", "TeeDetailSink"),
    "TeeTraceSink": ("ai_workflow_engine.engine", "TeeTraceSink"),
    "TeeUsageSink": ("ai_workflow_engine.usage", "TeeUsageSink"),
    "ToolCallRequest": ("ai_workflow_engine.llm_protocol", "ToolCallRequest"),
    "ToolResult": ("ai_workflow_engine.llm_protocol", "ToolResult"),
    "ToolSpec": ("ai_workflow_engine.llm_protocol", "ToolSpec"),
    "TraceSink": ("ai_workflow_engine.engine", "TraceSink"),
    "Transition": ("ai_workflow_engine.workflow", "Transition"),
    "UnsupportedNodeError": ("ai_workflow_engine.executor", "UnsupportedNodeError"),
    "UsageSink": ("ai_workflow_engine.usage", "UsageSink"),
    "WEAK_MODEL_CLEANER": ("ai_workflow_engine.parsing", "WEAK_MODEL_CLEANER"),
    "WindowedMemory": ("ai_workflow_engine.memory", "WindowedMemory"),
    "WorkflowArtifact": ("ai_workflow_engine.models", "WorkflowArtifact"),
    "WorkflowBuilder": ("ai_workflow_engine.workflow", "WorkflowBuilder"),
    "WorkflowCheckpoint": ("ai_workflow_engine.models", "WorkflowCheckpoint"),
    "WorkflowConfigBundle": ("ai_workflow_engine.config_loader", "WorkflowConfigBundle"),
    "WorkflowConfigError": ("ai_workflow_engine.config_loader", "WorkflowConfigError"),
    "WorkflowConfigLoader": ("ai_workflow_engine.config_loader", "WorkflowConfigLoader"),
    "WorkflowDecisionPlanner": ("ai_workflow_engine.engine", "WorkflowDecisionPlanner"),
    "WorkflowDefinition": ("ai_workflow_engine.workflow", "WorkflowDefinition"),
    "WorkflowEngine": ("ai_workflow_engine.builder", "WorkflowEngine"),
    "WorkflowEngineBuilder": ("ai_workflow_engine.builder", "WorkflowEngineBuilder"),
    "WorkflowExecutor": ("ai_workflow_engine.executor", "WorkflowExecutor"),
    "WorkflowGoal": ("ai_workflow_engine.models", "WorkflowGoal"),
    "WorkflowInstrument": ("ai_workflow_engine.engine", "WorkflowInstrument"),
    "WorkflowInstrumentRegistry": ("ai_workflow_engine.engine", "WorkflowInstrumentRegistry"),
    "WorkflowLoopController": ("ai_workflow_engine.engine", "WorkflowLoopController"),
    "WorkflowNode": ("ai_workflow_engine.workflow", "WorkflowNode"),
    "WorkflowPack": ("ai_workflow_engine.builder", "WorkflowPack"),
    "WorkflowProfile": ("ai_workflow_engine.models", "WorkflowProfile"),
    "WorkflowResult": ("ai_workflow_engine.models", "WorkflowResult"),
    "WorkflowRunResult": ("ai_workflow_engine.executor", "WorkflowRunResult"),
    "WorkflowRunner": ("ai_workflow_engine.engine", "WorkflowRunner"),
    "WorkflowScheduler": ("ai_workflow_engine.engine", "WorkflowScheduler"),
    "WorkflowStepPlanner": ("ai_workflow_engine.engine", "WorkflowStepPlanner"),
    "WorkflowSupervisor": ("ai_workflow_engine.engine", "WorkflowSupervisor"),
    "WorkflowTraceEvent": ("ai_workflow_engine.models", "WorkflowTraceEvent"),
    "WorkflowUsageEvent": ("ai_workflow_engine.models", "WorkflowUsageEvent"),
    "WorkflowUsageSummary": ("ai_workflow_engine.models", "WorkflowUsageSummary"),
    "WorkflowValidationError": ("ai_workflow_engine.workflow", "WorkflowValidationError"),
    "artifact_result": ("ai_workflow_engine.engine", "artifact_result"),
    "assert_checkpoint_payload_safe": ("ai_workflow_engine.engine", "assert_checkpoint_payload_safe"),
    "assert_no_config_secrets": ("ai_workflow_engine.config_loader", "assert_no_config_secrets"),
    "build_definition_from_artifact": ("ai_workflow_engine.flow_authoring", "build_definition_from_artifact"),
    "build_flow_author_capability": ("ai_workflow_engine.flow_authoring", "build_flow_author_capability"),
    "build_llm_agent_capability": ("ai_workflow_engine.engine", "build_llm_agent_capability"),
    "capability_context_for_goal": ("ai_workflow_engine.engine", "capability_context_for_goal"),
    "cleanup_artifacts": ("ai_workflow_engine.engine", "cleanup_artifacts"),
    "compose_cleaners": ("ai_workflow_engine.parsing", "compose_cleaners"),
    "current_model_profile": ("ai_workflow_engine.model_binding", "current_model_profile"),
    "default_rule_based_compactor": ("ai_workflow_engine.memory", "default_rule_based_compactor"),
    "default_state_renderer": ("ai_workflow_engine.memory", "default_state_renderer"),
    "default_tool_state_reducer": ("ai_workflow_engine.memory", "default_tool_state_reducer"),
    "extract_fenced_json": ("ai_workflow_engine.parsing", "extract_fenced_json"),
    "extract_first_json_object": ("ai_workflow_engine.parsing", "extract_first_json_object"),
    "format_trace_events": ("ai_workflow_engine.engine", "format_trace_events"),
    "gather_capabilities": ("ai_workflow_engine.engine", "gather_capabilities"),
    "is_plain_llm_callable": ("ai_workflow_engine.llm_protocol", "is_plain_llm_callable"),
    "load_prompt_template": ("ai_workflow_engine.prompt_loader", "load_prompt_template"),
    "load_workflow_config": ("ai_workflow_engine.config_loader", "load_workflow_config"),
    "model_profile_scope": ("ai_workflow_engine.model_binding", "model_profile_scope"),
    "open_observation_run_bundle": ("ai_workflow_engine.observation_bundle", "open_observation_run_bundle"),
    "prune_observation_bundles": ("ai_workflow_engine.observation_bundle", "prune_observation_bundles"),
    "render_capability_catalog": ("ai_workflow_engine.flow_authoring", "render_capability_catalog"),
    "render_full_replay_messages": ("ai_workflow_engine.memory", "render_full_replay_messages"),
    "render_machine_card": ("ai_workflow_engine.workflow", "render_machine_card"),
    "render_plan": ("ai_workflow_engine.planning", "render_plan"),
    "render_prompt_manifest": ("ai_workflow_engine.viz", "render_prompt_manifest"),
    "resolve_agent_memory": ("ai_workflow_engine.memory", "resolve_agent_memory"),
    "run_single_llm": ("ai_workflow_engine.convenience", "run_single_llm"),
    "run_single_step": ("ai_workflow_engine.convenience", "run_single_step"),
    "strip_think_tags": ("ai_workflow_engine.parsing", "strip_think_tags"),
}

__all__ = [
    "run_single_llm",
    "run_single_step",
    "END",
    "BranchDecision",
    "Fallback",
    "Replan",
    "Retrace",
    "Retry",
    "SubworkflowRef",
    "WorkflowBuilder",
    "WorkflowDefinition",
    "Transition",
    "render_machine_card",
    "render_capability_catalog",
    "MachineSnapshot",
    "WorkflowNode",
    "WorkflowValidationError",
    "CapabilityBindingError",
    "NodeExecutionState",
    "NodeExecutionServices",
    "NodeResult",
    "NodeSchedulingServices",
    "UnsupportedNodeError",
    "WorkflowExecutor",
    "WorkflowRunResult",
    "WorkflowEngine",
    "WorkflowEngineBuilder",
    "WorkflowPack",
    "PlanArtifact",
    "PlanTask",
    "AgentCapability",
    "AgentEpisodePlanner",
    "AgentRunRequest",
    "AgentRunResult",
    "AgentStepDecision",
    "AgentToolCall",
    "AgentToolStep",
    "PromptRef",
    "PromptRenderError",
    "PromptRenderResult",
    "PromptRenderService",
    "PromptRenderer",
    "PromptTemplateLoader",
    "CapabilityContext",
    "CapabilityResult",
    "CapabilityRegistry",
    "CapabilityRuntime",
    "CapabilitySpec",
    "CapabilityCall",
    "CallbackTraceSink",
    "AsyncQueueDetailSink",
    "AsyncQueueTraceSink",
    "DetailSink",
    "CheckpointStore",
    "EvidenceRef",
    "ExternalWriteRequest",
    "ExternalWriteResult",
    "ClarificationOption",
    "HumanClarificationRequest",
    "HumanClarificationResponse",
    "InMemoryTraceSink",
    "InMemoryDetailSink",
    "InMemoryCheckpointStore",
    "JsonlTraceSink",
    "JsonlDetailSink",
    "JsonlCheckpointStore",
    "TeeDetailSink",
    "TeeTraceSink",
    "ModelProfile",
    "ObservationConfig",
    "ObservationDetail",
    "ObservationRunBundle",
    "ObservationSequence",
    "RuntimePlan",
    "RuntimePlanCompiler",
    "SessionState",
    "WorkflowArtifact",
    "WorkflowCheckpoint",
    "WorkflowGoal",
    "WorkflowProfile",
    "WorkflowResult",
    "WorkflowTraceEvent",
    "WorkflowUsageEvent",
    "WorkflowUsageSummary",
    "WorkflowConfigBundle",
    "WorkflowConfigError",
    "WorkflowConfigLoader",
    "ExternalAdapterCapability",
    "EvaluationController",
    "EvaluationPlanner",
    "InMemoryExternalWriteSink",
    "JsonlExternalWriteSink",
    "ExternalProcessCapability",
    "ExternalProcessRequest",
    "HumanClarificationCapability",
    "HumanClarificationChannel",
    "InMemoryHumanClarificationChannel",
    "StructuredLLMNode",
    "StructuredOutputError",
    "WorkflowLoopController",
    "WorkflowStepPlanner",
    "TraceSink",
    "WorkflowDecisionPlanner",
    "WorkflowInstrument",
    "WorkflowInstrumentRegistry",
    "WorkflowRunner",
    "SchedulingDecision",
    "WorkflowScheduler",
    "WorkflowSupervisor",
    "artifact_result",
    "assert_checkpoint_payload_safe",
    "capability_context_for_goal",
    "format_trace_events",
    "gather_capabilities",
    "cleanup_artifacts",
    "assert_no_config_secrets",
    "load_workflow_config",
    "load_prompt_template",
    "WEAK_MODEL_CLEANER",
    "compose_cleaners",
    "extract_fenced_json",
    "extract_first_json_object",
    "strip_think_tags",
    "ImageInput",
    "StructuredVisionLLMNode",
    "AgentMemory",
    "AgentMemoryRenderContext",
    "CompactingMemory",
    "StructuredStateMemory",
    "WindowedMemory",
    "default_rule_based_compactor",
    "default_state_renderer",
    "default_tool_state_reducer",
    "FullReplayMemory",
    "ImageEvictingMemory",
    "InMemoryMemoryStore",
    "MemoryNamespace",
    "MemoryRecord",
    "MemoryStore",
    "resolve_agent_memory",
    "render_full_replay_messages",
    "ChatMessage",
    "LLMCallable",
    "LLMRequest",
    "LLMResponse",
    "ToolCallRequest",
    "ToolResult",
    "ToolSpec",
    "is_plain_llm_callable",
    "current_model_profile",
    "model_profile_scope",
    "render_plan",
    "PromptCapturingLLMClient",
    "UsageSink",
    "InMemoryUsageSink",
    "JsonlUsageSink",
    "SequencedDetailSink",
    "SequencedTraceSink",
    "SequencedUsageSink",
    "AsyncQueueUsageSink",
    "TeeUsageSink",
    "open_observation_run_bundle",
    "prune_observation_bundles",
    "BranchFlowNode",
    "DEFAULT_FLOW_AUTHOR_PROMPT",
    "EvaluateFlowNode",
    "FanoutFlowNode",
    "FlowArtifact",
    "FlowNode",
    "StepFlowNode",
    "FlowAuthorRequest",
    "FlowNodeSpec",
    "build_flow_author_capability",
    "build_definition_from_artifact",
    "render_prompt_manifest",
]


def __getattr__(name: str) -> Any:
    try:
        module_path, attr = _EXPORTS[name]
    except KeyError:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from None
    value = getattr(import_module(module_path), attr)
    globals()[name] = value  # cache: subsequent access skips __getattr__
    return value


def __dir__() -> list[str]:
    return sorted(set(__all__) | set(globals()))
